/* tslint:disable */
/* eslint-disable */
/**
 * admin API
 * api for the needs of the admin backoffice
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vincent.serpoul@triple-a.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MedianFxRateV1,
  ProblemDetail,
} from '../models/index';
import {
    MedianFxRateV1FromJSON,
    MedianFxRateV1ToJSON,
    ProblemDetailFromJSON,
    ProblemDetailToJSON,
} from '../models/index';

/**
 * 
 */
export class RatesApi extends runtime.BaseAPI {

    /**
     * get latest rates for all supported currencies
     * get latest rates
     */
    async getLatestRatesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: MedianFxRateV1; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/api/v1/rates`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => runtime.mapValues(jsonValue, MedianFxRateV1FromJSON));
    }

    /**
     * get latest rates for all supported currencies
     * get latest rates
     */
    async getLatestRates(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: MedianFxRateV1; }> {
        const response = await this.getLatestRatesRaw(initOverrides);
        return await response.value();
    }

}
