/* tslint:disable */
/* eslint-disable */
/**
 * admin API
 * api for the needs of the admin backoffice
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vincent.serpoul@triple-a.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Transaction } from './Transaction';
import {
    TransactionFromJSON,
    TransactionFromJSONTyped,
    TransactionToJSON,
} from './Transaction';

/**
 * details of the account
 * @export
 * @interface AccountDetails
 */
export interface AccountDetails {
    /**
     * account id on the ledger
     * @type {string}
     * @memberof AccountDetails
     */
    id?: string;
    /**
     * 
     * @type {Array<Transaction>}
     * @memberof AccountDetails
     */
    transactions?: Array<Transaction>;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof AccountDetails
     */
    balances?: { [key: string]: string; };
}

/**
 * Check if a given object implements the AccountDetails interface.
 */
export function instanceOfAccountDetails(value: object): value is AccountDetails {
    return true;
}

export function AccountDetailsFromJSON(json: any): AccountDetails {
    return AccountDetailsFromJSONTyped(json, false);
}

export function AccountDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'transactions': json['transactions'] == null ? undefined : ((json['transactions'] as Array<any>).map(TransactionFromJSON)),
        'balances': json['balances'] == null ? undefined : json['balances'],
    };
}

export function AccountDetailsToJSON(value?: AccountDetails | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'transactions': value['transactions'] == null ? undefined : ((value['transactions'] as Array<any>).map(TransactionToJSON)),
        'balances': value['balances'],
    };
}

