/* tslint:disable */
/* eslint-disable */
/**
 * admin API
 * api for the needs of the admin backoffice
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vincent.serpoul@triple-a.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountryCode2 } from './CountryCode2';
import {
    CountryCode2FromJSON,
    CountryCode2FromJSONTyped,
    CountryCode2ToJSON,
} from './CountryCode2';

/**
 * 
 * @export
 * @interface CreateEntityCorporate
 */
export interface CreateEntityCorporate {
    /**
     * 
     * @type {string}
     * @memberof CreateEntityCorporate
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityCorporate
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityCorporate
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityCorporate
     */
    postalCode?: string;
    /**
     * 
     * @type {CountryCode2}
     * @memberof CreateEntityCorporate
     */
    country?: CountryCode2;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityCorporate
     */
    companyName?: string;
    /**
     * 
     * @type {CountryCode2}
     * @memberof CreateEntityCorporate
     */
    registrationCountry?: CountryCode2;
    /**
     * 
     * @type {Date}
     * @memberof CreateEntityCorporate
     */
    incorporationDate?: Date;
}

/**
 * Check if a given object implements the CreateEntityCorporate interface.
 */
export function instanceOfCreateEntityCorporate(value: object): value is CreateEntityCorporate {
    return true;
}

export function CreateEntityCorporateFromJSON(json: any): CreateEntityCorporate {
    return CreateEntityCorporateFromJSONTyped(json, false);
}

export function CreateEntityCorporateFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEntityCorporate {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'street': json['street'] == null ? undefined : json['street'],
        'city': json['city'] == null ? undefined : json['city'],
        'postalCode': json['postal_code'] == null ? undefined : json['postal_code'],
        'country': json['country'] == null ? undefined : CountryCode2FromJSON(json['country']),
        'companyName': json['company_name'] == null ? undefined : json['company_name'],
        'registrationCountry': json['registration_country'] == null ? undefined : CountryCode2FromJSON(json['registration_country']),
        'incorporationDate': json['incorporation_date'] == null ? undefined : (new Date(json['incorporation_date'])),
    };
}

export function CreateEntityCorporateToJSON(value?: CreateEntityCorporate | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'street': value['street'],
        'city': value['city'],
        'postal_code': value['postalCode'],
        'country': CountryCode2ToJSON(value['country']),
        'company_name': value['companyName'],
        'registration_country': CountryCode2ToJSON(value['registrationCountry']),
        'incorporation_date': value['incorporationDate'] == null ? undefined : ((value['incorporationDate']).toISOString().substring(0,10)),
    };
}

