/* tslint:disable */
/* eslint-disable */
/**
 * admin API
 * api for the needs of the admin backoffice
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vincent.serpoul@triple-a.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CountryCode2 } from './CountryCode2';
import {
    CountryCode2FromJSON,
    CountryCode2FromJSONTyped,
    CountryCode2ToJSON,
} from './CountryCode2';
import type { Gender } from './Gender';
import {
    GenderFromJSON,
    GenderFromJSONTyped,
    GenderToJSON,
} from './Gender';

/**
 * 
 * @export
 * @interface CreateEntityIndividual
 */
export interface CreateEntityIndividual {
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    email?: string;
    /**
     * 
     * @type {Gender}
     * @memberof CreateEntityIndividual
     */
    gender?: Gender;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    street?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    city?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    zipCode?: string;
    /**
     * 
     * @type {CountryCode2}
     * @memberof CreateEntityIndividual
     */
    country?: CountryCode2;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    nationality?: string;
    /**
     * 
     * @type {CountryCode2}
     * @memberof CreateEntityIndividual
     */
    birthCountry?: CountryCode2;
    /**
     * 
     * @type {Date}
     * @memberof CreateEntityIndividual
     */
    birthDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof CreateEntityIndividual
     */
    birthPlace?: string;
}

/**
 * Check if a given object implements the CreateEntityIndividual interface.
 */
export function instanceOfCreateEntityIndividual(value: object): value is CreateEntityIndividual {
    return true;
}

export function CreateEntityIndividualFromJSON(json: any): CreateEntityIndividual {
    return CreateEntityIndividualFromJSONTyped(json, false);
}

export function CreateEntityIndividualFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateEntityIndividual {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'gender': json['gender'] == null ? undefined : GenderFromJSON(json['gender']),
        'firstName': json['first_name'] == null ? undefined : json['first_name'],
        'lastName': json['last_name'] == null ? undefined : json['last_name'],
        'street': json['street'] == null ? undefined : json['street'],
        'city': json['city'] == null ? undefined : json['city'],
        'zipCode': json['zip_code'] == null ? undefined : json['zip_code'],
        'country': json['country'] == null ? undefined : CountryCode2FromJSON(json['country']),
        'nationality': json['nationality'] == null ? undefined : json['nationality'],
        'birthCountry': json['birth_country'] == null ? undefined : CountryCode2FromJSON(json['birth_country']),
        'birthDate': json['birth_date'] == null ? undefined : (new Date(json['birth_date'])),
        'birthPlace': json['birth_place'] == null ? undefined : json['birth_place'],
    };
}

export function CreateEntityIndividualToJSON(value?: CreateEntityIndividual | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'email': value['email'],
        'gender': GenderToJSON(value['gender']),
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'street': value['street'],
        'city': value['city'],
        'zip_code': value['zipCode'],
        'country': CountryCode2ToJSON(value['country']),
        'nationality': value['nationality'],
        'birth_country': CountryCode2ToJSON(value['birthCountry']),
        'birth_date': value['birthDate'] == null ? undefined : ((value['birthDate']).toISOString().substring(0,10)),
        'birth_place': value['birthPlace'],
    };
}

