/* tslint:disable */
/* eslint-disable */
/**
 * admin API
 * api for the needs of the admin backoffice
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vincent.serpoul@triple-a.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Corporate } from './Corporate';
import {
    instanceOfCorporate,
    CorporateFromJSON,
    CorporateFromJSONTyped,
    CorporateToJSON,
} from './Corporate';
import type { Individual } from './Individual';
import {
    instanceOfIndividual,
    IndividualFromJSON,
    IndividualFromJSONTyped,
    IndividualToJSON,
} from './Individual';

/**
 * @type Entity
 * 
 * @export
 */
export type Entity = Corporate | Individual;

export function EntityFromJSON(json: any): Entity {
    return EntityFromJSONTyped(json, false);
}

export function EntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Entity {
    if (json == null) {
        return json;
    }
    if (instanceOfCorporate(json)) {
        return CorporateFromJSONTyped(json, true);
    }
    if (instanceOfIndividual(json)) {
        return IndividualFromJSONTyped(json, true);
    }
}

export function EntityToJSON(value?: Entity | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfCorporate(value)) {
        return CorporateToJSON(value as Corporate);
    }
    if (instanceOfIndividual(value)) {
        return IndividualToJSON(value as Individual);
    }

    return {};
}

