/* tslint:disable */
/* eslint-disable */
/**
 * admin API
 * api for the needs of the admin backoffice
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vincent.serpoul@triple-a.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MedianFxRateV1
 */
export interface MedianFxRateV1 {
    /**
     * 
     * @type {number}
     * @memberof MedianFxRateV1
     */
    version?: number;
    /**
     * 
     * @type {string}
     * @memberof MedianFxRateV1
     */
    id?: string;
    /**
     * 
     * @type {{ [key: string]: number; }}
     * @memberof MedianFxRateV1
     */
    providersContrib?: { [key: string]: number; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MedianFxRateV1
     */
    providersMedians?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof MedianFxRateV1
     */
    ratesCount?: number;
    /**
     * 
     * @type {number}
     * @memberof MedianFxRateV1
     */
    outliersPerc?: number;
    /**
     * 
     * @type {string}
     * @memberof MedianFxRateV1
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof MedianFxRateV1
     */
    base?: string;
    /**
     * 
     * @type {string}
     * @memberof MedianFxRateV1
     */
    quote?: string;
    /**
     * 
     * @type {string}
     * @memberof MedianFxRateV1
     */
    rateBaseQuote?: string;
    /**
     * 
     * @type {string}
     * @memberof MedianFxRateV1
     */
    rateBaseUsd?: string;
    /**
     * 
     * @type {string}
     * @memberof MedianFxRateV1
     */
    rateUsdQuote?: string;
}

/**
 * Check if a given object implements the MedianFxRateV1 interface.
 */
export function instanceOfMedianFxRateV1(value: object): value is MedianFxRateV1 {
    return true;
}

export function MedianFxRateV1FromJSON(json: any): MedianFxRateV1 {
    return MedianFxRateV1FromJSONTyped(json, false);
}

export function MedianFxRateV1FromJSONTyped(json: any, ignoreDiscriminator: boolean): MedianFxRateV1 {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'id': json['id'] == null ? undefined : json['id'],
        'providersContrib': json['providers_contrib'] == null ? undefined : json['providers_contrib'],
        'providersMedians': json['providers_medians'] == null ? undefined : json['providers_medians'],
        'ratesCount': json['rates_count'] == null ? undefined : json['rates_count'],
        'outliersPerc': json['outliers_perc'] == null ? undefined : json['outliers_perc'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'base': json['base'] == null ? undefined : json['base'],
        'quote': json['quote'] == null ? undefined : json['quote'],
        'rateBaseQuote': json['rate_base_quote'] == null ? undefined : json['rate_base_quote'],
        'rateBaseUsd': json['rate_base_usd'] == null ? undefined : json['rate_base_usd'],
        'rateUsdQuote': json['rate_usd_quote'] == null ? undefined : json['rate_usd_quote'],
    };
}

export function MedianFxRateV1ToJSON(value?: MedianFxRateV1 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'version': value['version'],
        'id': value['id'],
        'providers_contrib': value['providersContrib'],
        'providers_medians': value['providersMedians'],
        'rates_count': value['ratesCount'],
        'outliers_perc': value['outliersPerc'],
        'created_at': value['createdAt'],
        'base': value['base'],
        'quote': value['quote'],
        'rate_base_quote': value['rateBaseQuote'],
        'rate_base_usd': value['rateBaseUsd'],
        'rate_usd_quote': value['rateUsdQuote'],
    };
}

