/* tslint:disable */
/* eslint-disable */
/**
 * admin API
 * api for the needs of the admin backoffice
 *
 * The version of the OpenAPI document: 1.0
 * Contact: vincent.serpoul@triple-a.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * ledger transaction
 * @export
 * @interface Transaction
 */
export interface Transaction {
    /**
     * account id on the ledger
     * @type {string}
     * @memberof Transaction
     */
    fromAccountId: string;
    /**
     * account id on the ledger
     * @type {string}
     * @memberof Transaction
     */
    toAccountId: string;
    /**
     * decimals 0.000001
     * @type {string}
     * @memberof Transaction
     */
    amount: string;
    /**
     * decimals 0.000001
     * @type {string}
     * @memberof Transaction
     */
    amountUsd: string;
    /**
     * 
     * @type {Date}
     * @memberof Transaction
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the Transaction interface.
 */
export function instanceOfTransaction(value: object): value is Transaction {
    if (!('fromAccountId' in value) || value['fromAccountId'] === undefined) return false;
    if (!('toAccountId' in value) || value['toAccountId'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('amountUsd' in value) || value['amountUsd'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function TransactionFromJSON(json: any): Transaction {
    return TransactionFromJSONTyped(json, false);
}

export function TransactionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transaction {
    if (json == null) {
        return json;
    }
    return {
        
        'fromAccountId': json['from_account_id'],
        'toAccountId': json['to_account_id'],
        'amount': json['amount'],
        'amountUsd': json['amount_usd'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function TransactionToJSON(value?: Transaction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from_account_id': value['fromAccountId'],
        'to_account_id': value['toAccountId'],
        'amount': value['amount'],
        'amount_usd': value['amountUsd'],
        'created_at': ((value['createdAt']).toISOString()),
    };
}

